inveniosoftware/invenio-rdm-migrator

- invenio_rdm_migrator/load/postgresql.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/records/table_generator.py
- invenio_rdm_migrator/streams/records/transform.py
After making a successful run of the zenodo-rdm records stream this minor fixes were needed.
```
Execution time: 0:00:37.617660
```
> Minor fixes

- invenio_rdm_migrator/load/postgresql.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/records/models.py
- invenio_rdm_migrator/streams/records/table_generator.py
addresses https://github.com/zenodo/zenodo-rdm/issues/111
> load: add parent communities

- invenio_rdm_migrator/streams/records/transform.py
- closes https://github.com/zenodo/zenodo-rdm/issues/201
> records: add custom fields to transformer

- invenio_rdm_migrator/__init__.py
- invenio_rdm_migrator/streams/records/table_generator.py
- invenio_rdm_migrator/streams/records/transform.py
> Record transform

- invenio_rdm_migrator/load/ids.py
- invenio_rdm_migrator/load/postgresql.py
- invenio_rdm_migrator/streams/cache.py
- invenio_rdm_migrator/streams/communities/load.py
- invenio_rdm_migrator/streams/communities/table_generator.py
- invenio_rdm_migrator/streams/files/load.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/records/table_generators/__init__.py
- invenio_rdm_migrator/streams/records/table_generators/drafts.py
- invenio_rdm_migrator/streams/records/table_generators/parents.py
- invenio_rdm_migrator/streams/records/table_generators/records.py
- invenio_rdm_migrator/streams/records/table_generators/versions.py
- invenio_rdm_migrator/streams/requests/load.py
- invenio_rdm_migrator/streams/requests/table_generator.py
- invenio_rdm_migrator/streams/runner.py
- invenio_rdm_migrator/streams/users/load.py
- tests/conftest.py
- tests/streams/communities/test_communities_load.py
- tests/streams/files/test_files_load.py
- tests/streams/requests/test_requests_load.py
- closes https://github.com/zenodo/zenodo-rdm/issues/241
> records: add logic to migrate drafts

- invenio_rdm_migrator/streams/cache.py
- invenio_rdm_migrator/streams/records/table_generators/drafts.py
- invenio_rdm_migrator/streams/records/table_generators/records.py
- invenio_rdm_migrator/transform/__init__.py
- invenio_rdm_migrator/transform/base.py
- closes https://github.com/zenodo/zenodo-rdm/issues/241
> drafts versioning

- invenio_rdm_migrator/load/ids.py
- invenio_rdm_migrator/streams/records/table_generators/drafts.py
- closes https://github.com/zenodo/zenodo-rdm/issues/241
> drafts: yield reserved pids

- invenio_rdm_migrator/__init__.py
- invenio_rdm_migrator/load/ids.py
- invenio_rdm_migrator/load/postgresql.py
- load: fix autoincrementing PK generation
- release: v1.0.0a7
> Fix serial PK generation and release v1.0.0a7

- invenio_rdm_migrator/streams/streams.py
> stream: default to dummy classes for extract and transform

- invenio_rdm_migrator/load/postgresql.py
- invenio_rdm_migrator/streams/cache.py
- invenio_rdm_migrator/streams/records/table_generators/records.py
- invenio_rdm_migrator/streams/runner.py
- invenio_rdm_migrator/utils.py
- tests/streams/test_cache.py
- closes https://github.com/inveniosoftware/invenio-rdm-migrator/issues/61
> cache: dump cache on runner exception

- invenio_rdm_migrator/streams/records/transform.py
- invenio_rdm_migrator/streams/runner.py
- invenio_rdm_migrator/streams/streams.py
- invenio_rdm_migrator/transform/base.py
> stream: add error logging on transformation step

- invenio_rdm_migrator/streams/records/table_generators/drafts.py
- invenio_rdm_migrator/streams/records/table_generators/records.py
- invenio_rdm_migrator/streams/records/transform.py
- invenio_rdm_migrator/streams/runner.py
- invenio_rdm_migrator/transform/base.py
- tests/streams/records/conftest.py
- tests/streams/records/test_records_table_generator.py
> doi: changes on drafts

- invenio_rdm_migrator/__init__.py
- tests/streams/records/test_records_table_generator.py
> release: v1.0.0a9

- invenio_rdm_migrator/streams/records/table_generators/records.py
> records: fix record uuid preservation

- invenio_rdm_migrator/load/ids.py
- invenio_rdm_migrator/streams/cache.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/records/table_generators/drafts.py
- invenio_rdm_migrator/streams/runner.py
- invenio_rdm_migrator/streams/streams.py
> drafts: add max pid counter cache so it can be loaded separately

- invenio_rdm_migrator/load/ids.py
- invenio_rdm_migrator/streams/cache.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/records/table_generators/drafts.py
- invenio_rdm_migrator/streams/runner.py
> streams: fix max pid cache

- invenio_rdm_migrator/streams/communities/__init__.py
- invenio_rdm_migrator/streams/communities/models.py
- invenio_rdm_migrator/streams/communities/table_generator.py
- invenio_rdm_migrator/streams/communities/transform.py
- tests/streams/communities/conftest.py
- tests/streams/communities/test_communities_load.py
- tests/streams/communities/test_communities_table_generator.py
- tests/streams/communities/test_communities_transform.py
closes https://github.com/zenodo/zenodo-rdm/issues/312
> files: added community files

- invenio_rdm_migrator/__init__.py
> release: v1.0.0a10

- invenio_rdm_migrator/streams/records/load.py
- closes https://github.com/inveniosoftware/invenio-rdm-migrator/issues/75
> records: make versioning optional

- invenio_rdm_migrator/load/postgresql.py
- invenio_rdm_migrator/streams/communities/load.py
- invenio_rdm_migrator/streams/files/load.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/requests/load.py
- invenio_rdm_migrator/streams/runner.py
- invenio_rdm_migrator/streams/streams.py
- invenio_rdm_migrator/streams/users/load.py
- tests/streams/communities/test_communities_load.py
- tests/streams/files/test_files_load.py
- tests/streams/requests/test_requests_load.py
- closes https://github.com/inveniosoftware/invenio-rdm-migrator/issues/79
> load, postgresql: support loading data from existing csv files

- invenio_rdm_migrator/streams/cache/__init__.py
- invenio_rdm_migrator/streams/cache/base.py
- invenio_rdm_migrator/streams/cache/communities.py
- invenio_rdm_migrator/streams/cache/pids.py
- invenio_rdm_migrator/streams/cache/records.py
- invenio_rdm_migrator/streams/communities/load.py
- invenio_rdm_migrator/streams/communities/table_generator.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/requests/load.py
- invenio_rdm_migrator/streams/requests/table_generator.py
- invenio_rdm_migrator/streams/runner.py
- tests/conftest.py
- tests/streams/communities/test_communities_table_generator.py
- tests/streams/test_cache.py
> Cache consolidation

- invenio_rdm_migrator/__init__.py
> release: v1.0.0a11

- invenio_rdm_migrator/load/postgresql.py
- invenio_rdm_migrator/logging.py
- invenio_rdm_migrator/state/base.py
- invenio_rdm_migrator/streams/records/table_generators/records.py
- invenio_rdm_migrator/streams/records/transform.py
- invenio_rdm_migrator/streams/runner.py
- invenio_rdm_migrator/streams/streams.py
- invenio_rdm_migrator/transform/base.py
- closes https://github.com/inveniosoftware/invenio-rdm-migrator/issues/93
> logging: replace prints by logging

- invenio_rdm_migrator/extract/__init__.py
- invenio_rdm_migrator/extract/identity.py
- invenio_rdm_migrator/load/__init__.py
- invenio_rdm_migrator/load/postgresql.py
- invenio_rdm_migrator/streams/streams.py
- invenio_rdm_migrator/transform/__init__.py
- invenio_rdm_migrator/transform/identity.py
- tests/load/test_postgresql.py
- tests/transform/test_identity.py
This is an independent PR that adds functionality required for the OAuth migration, however, it has been separated to avoid having a monster PR.
> Identity cls

- invenio_rdm_migrator/load/postgresql.py
- invenio_rdm_migrator/streams/communities/load.py
- invenio_rdm_migrator/streams/files/load.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/requests/load.py
- invenio_rdm_migrator/streams/runner.py
- invenio_rdm_migrator/streams/users/load.py
- tests/load/test_postgresql.py
- tests/streams/communities/test_communities_load.py
- tests/streams/files/test_files_load.py
- tests/streams/requests/test_requests_load.py
give more granularity to the existing data flags, it would support the following use cases:
- Load fully with transformation, from NON existing data
- Load fully from existing data
- Load some tg from existing data and some with trasnformation
> load: existing_data at tg level with possible load overwrite

- invenio_rdm_migrator/load/postgresql.py
- invenio_rdm_migrator/streams/oauth/__init__.py
- invenio_rdm_migrator/streams/oauth/load.py
- invenio_rdm_migrator/streams/oauth/models.py
- invenio_rdm_migrator/streams/oauth/transform.py
- invenio_rdm_migrator/streams/runner.py
- invenio_rdm_migrator/transform/__init__.py
- invenio_rdm_migrator/transform/encrypt.py
- setup.cfg
- tests/transform/test_encrypt.py
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/106
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/107
- closes https://github.com/zenodo/zenodo-rdm/issues/246
The first 4 commits belong to the required PR, review only the last one (_streams: oauth..._)
> streams: add OAuth models

- invenio_rdm_migrator/__init__.py
> release: v1.0.0a14

- invenio_rdm_migrator/__init__.py
> release: v1.0.0

- invenio_rdm_migrator/actions/base.py
- invenio_rdm_migrator/load/postgresql/transactions/execute.py
- invenio_rdm_migrator/load/postgresql/transactions/operations.py
- invenio_rdm_migrator/state.py
- invenio_rdm_migrator/streams/actions/__init__.py
- invenio_rdm_migrator/streams/actions/drafts.py
- invenio_rdm_migrator/streams/actions/parents.py
- invenio_rdm_migrator/streams/actions/users.py
- invenio_rdm_migrator/streams/models/users.py
- invenio_rdm_migrator/utils.py
- run-tests.sh
- setup.cfg
- tests/conftest.py
- tests/load/test_load_bulk.py
- tests/load/test_load_transactions.py
- tests/streams/actions/test_drafts_actions.py
- tests/streams/actions/test_user_actions.py
- tests/test_utils.py
- tests/transform/test_encrypt.py
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/issues/114
- closes https://github.com/zenodo/zenodo-rdm/issues/424
All the previous ones are ready to go 🚀
> User actions

- invenio_rdm_migrator/load/postgresql/transactions/execute.py
- invenio_rdm_migrator/streams/actions/load/__init__.py
- invenio_rdm_migrator/streams/actions/load/drafts.py
- tests/streams/actions/test_drafts_actions.py
- partly closes https://github.com/zenodo/zenodo-rdm/issues/428
> actions: add edit draft

- invenio_rdm_migrator/state.py
- invenio_rdm_migrator/streams/actions/load/__init__.py
- invenio_rdm_migrator/streams/actions/load/drafts.py
- invenio_rdm_migrator/streams/actions/load/files.py
- tests/streams/actions/conftest.py
- tests/streams/actions/test_drafts_actions.py
- tests/streams/actions/test_files_actions.py
- tests/test_state.py
- partly closes https://github.com/zenodo/zenodo-rdm/issues/428
> actions: add new draft publish

- CHANGES.rst
- invenio_rdm_migrator/__init__.py
- invenio_rdm_migrator/streams/models/records.py
- invenio_rdm_migrator/streams/models/users.py
- models: use defaults for NULL-able fields
- release: v4.4.1
> Nullable model fields fix and v4.4.1

- invenio_rdm_migrator/streams/actions/load/__init__.py
- invenio_rdm_migrator/streams/actions/load/oauth/__init__.py
- invenio_rdm_migrator/streams/actions/load/oauth/applications.py
- invenio_rdm_migrator/streams/actions/load/oauth/tokens.py
- invenio_rdm_migrator/streams/models/oauth.py
- invenio_rdm_migrator/streams/oauth/transform.py
- invenio_rdm_migrator/transform/__init__.py
- invenio_rdm_migrator/transform/identity.py
- tests/streams/actions/test_community_actions.py
- tests/streams/actions/test_files_actions.py
- tests/streams/actions/test_oauth_actions.py
- tests/transform/test_identity.py
- partially closes https://github.com/zenodo/zenodo-rdm/issues/433
> OAuth server incremental

- README.rst
- invenio_rdm_migrator/__init__.py
- invenio_rdm_migrator/state.py
- invenio_rdm_migrator/streams/oauth/__init__.py
- invenio_rdm_migrator/streams/oauth/load.py
- invenio_rdm_migrator/streams/oauth/transform.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/records/table_generators/drafts.py
- invenio_rdm_migrator/streams/records/table_generators/records.py
- invenio_rdm_migrator/streams/records/table_generators/utils.py
- invenio_rdm_migrator/streams/records/table_generators/versions.py
- invenio_rdm_migrator/streams/records/transform.py
- tests/streams/records/conftest.py
- tests/streams/records/test_records_table_generator.py
* Fixes parent community row generation to use parent state.
* Refactors record/draft (media) files insertion.
> records: fix communities and refactor files

- invenio_rdm_migrator/state.py
- invenio_rdm_migrator/streams/records/__init__.py
- invenio_rdm_migrator/streams/records/load.py
- invenio_rdm_migrator/streams/records/table_generators/records.py
- invenio_rdm_migrator/streams/records/transform.py
- invenio_rdm_migrator/streams/runner.py
- records: add tombstones and deletion status
- state: flush in-memory cache to in-memory SQLite DB
> Record tombstones and persist state between streams

- invenio_rdm_migrator/streams/actions/load/__init__.py
- invenio_rdm_migrator/streams/actions/load/github/__init__.py
- invenio_rdm_migrator/streams/actions/load/github/hooks.py
- invenio_rdm_migrator/streams/actions/load/github/releases.py
- invenio_rdm_migrator/streams/github/__init__.py
- invenio_rdm_migrator/streams/github/transform.py
- tests/streams/actions/test_github_actions.py
- partly closes https://github.com/zenodo/zenodo-rdm/issues/436
> actions: add hook enable/disable and update
